version: "3.8"

services:
  mysql:
    image: mysql:8.0.26
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3307:3306"
    platform: linux/x86_64

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    platform: linux/x86_64
